ssid=CT317_44a2
wpa_passphrase=1234567890
interface=eth2
ctrl_interface=/var/run/hostapd
channel=36
wpa=2
beacon_int=100
driver=nl80211
hw_mode=a
wme_enabled=1
ht_capab=[SHORT-GI-20][SHORT-GI-40][HT40+]
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
ieee80211n=1
max_num_sta=1
wpa_group_rekey=86400
country_code=CN
